### ISSUE TITLE
Problems when hitting NPC

### ISSUE THREAD

**Issue by Wgis** [JeannotM/DynamicDifficulty#1]
I have plugin Citizens2, and NPC type is Player. 
When i hit player, i got this error.

```
[01:45:17 ERROR]: Could not pass event EntityDamageByEntityEvent to DynamicDifficulty v1.5
java.lang.NullPointerException: Cannot invoke "me.skinnyjeans.gmd.models.Minecrafter.getAffinity()" because the return value of "java.util.HashMap.get(Object)" is null
        at me.skinnyjeans.gmd.Affinity.calcDifficulty(Affinity.java:806) ~[DynamicDifficulty v1.5.jar:?]
        at me.skinnyjeans.gmd.events.AffinityEvents.onHit(AffinityEvents.java:239) ~[DynamicDifficulty v1.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor50.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-59]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[paper-1.18.jar:git-Paper-59]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1116) ~[paper-1.18.jar:git-Paper-59]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:992) ~[paper-1.18.jar:git-Paper-59]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:948) ~[paper-1.18.jar:git-Paper-59]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1148) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2041) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1016) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1345) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:923) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1027) ~[?:?]
        at net.citizensnpcs.nms.v1_18_R1.entity.EntityHumanNPC.a(EntityHumanNPC.java:299) ~[Citizens-2.0.29-b2419.jar:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1263) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2035) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2501) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2428) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-59]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by JeannotM** [comment]
Thanks for leaving me this, pretty cool this was added via Github. I think I've fixed the issue glitching, but I also installed Citizens so I can further bugfix it. Thanks again!

**Comment by Wgis** [comment]
I make logic mistake. When i hit NPC with type Player. I got this error

**Comment by Wgis** [comment]
also can u update jar on bukkit when you done?

**Comment by JeannotM** [comment]
Oh yeah sorry, I think it's finished. I uploaded the Jar a few hours ago on the discord server, but will update it on Spigot too. https://discord.gg/eYDRtWV5kj
