### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to DynamicDifficulty v1.6

### ISSUE THREAD

**Issue by synrg** [JeannotM/DynamicDifficulty#11]
Our server suffered multiple crashes like this yesterday. I had to disable the plugin.

```
2022-10-08 12:56:01 | [ERROR] Could not pass event EntityDamageByEntityEvent to DynamicDifficulty v1.6
2022-10-08 12:56:01 | [RAW] java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R1.projectiles.CraftBlockProjectileSource cannot be cast to class org.bukkit.entity.Entity (org.bukkit.craftbukkit.v1_19_R1.projectiles.CraftBlockProjectileSource and org.bukkit.entity.Entity are in unnamed module of loader java.net.URLClassLoader @5c29bfd)
2022-10-08 12:56:01 | [RAW]     at me.skinnyjeans.gmd.events.EntityHitListener.onHit(EntityHitListener.java:43) ~[DynamicDifficulty v1.6.jar:?]
2022-10-08 12:56:01 | [RAW]     at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor34.execute(Unknown Source) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
2022-10-08 12:56:01 | [RAW]     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-194]
2022-10-08 12:56:01 | [RAW]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
2022-10-08 12:56:01 | [RAW]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
2022-10-08 12:56:01 | [RAW]     at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:249) ~[paper-1.19.2.jar:git-Paper-194]
2022-10-08 12:56:01 | [RAW]     at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1142) ~[paper-1.19.2.jar:git-Paper-194]
2022-10-08 12:56:01 | [RAW]     at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1001) ~[paper-1.19.2.jar:git-Paper-194]
2022-10-08 12:56:01 | [RAW]     at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:953) ~[paper-1.19.2.jar:git-Paper-194]
2022-10-08 12:56:01 | [RAW]     at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1176) ~[paper-1.19.2.jar:git-Paper-194]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2122) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1075) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1369) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.world.entity.player.Player.hurt(Player.java:982) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1025) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:412) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:181) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:172) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:306) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:242) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1190) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:728) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-194]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:708) ~[?:?]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.2.jar:git-Paper-194]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-194]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-194]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-194]
2022-10-08 12:56:01 | [RAW]     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-194]
2022-10-08 12:56:01 | [RAW]     at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by synrg** [comment]
Hmm. I had a look at the code, and Spigot, and it looks like you didn't consider the case when computing arrow hits where the arrow was shot from a dispenser (a non-Entity).

**Comment by JeannotM** [comment]
Damn, this is very unfortunate. I have some free time this weekend and I'll check it out then

**Comment by synrg** [comment]
I'd love to help. But I can't get your project to build.

**Comment by JeannotM** [comment]
Help is not really needed, unless you want to of course xd. but if you want the project to work on your computer you'll need to either disable or manually add PlaceholderAPI and also change the Java Directory folder in the pom.xml on line 61

**Comment by synrg** [comment]
My goal is educating myself in building any of the third-party plugins we use on our servers so that I can provide more useful input to developers / fully tested patches as needed. It's possible my build issues stem from trying to use openjdk instead of sun jdk.

Thanks for the tips. The change needed in pom.xml was fairly self-evident. I am probably not yet finding problems with PlaceholderAPI because my broken build environment prevents the build from getting that far. I'll see if I can work it out on my own. Certainly this issue is the wrong place for further discussion on fixing my build environment.

**Comment by synrg** [comment]
After much messing around with pom.xml and ripping out stuff that doesn't seem to work with my JDK, I got it to build. I never could get proguard to work for me so I tore it out. I then had to add `<sourceDirectory>src</sourceDirectory>` to the build and set the source & target for the maven-compiler-plugin both to 17 to match my jdk version. Finally I had to include the .yml files into the resources dir which I manually created.

Additionally, I experimentally bumped up all of the plugin and dependency versions to latest available from spigot & maven central and everything seems to build fine.

This patch seems to work:

```java
diff --git a/src/me/skinnyjeans/gmd/events/EntityHitListener.java b/src/me/skinnyjeans/gmd/events/EntityHitListener.java
index 849a6f7..1145b5f 100644
--- a/src/me/skinnyjeans/gmd/events/EntityHitListener.java
+++ b/src/me/skinnyjeans/gmd/events/EntityHitListener.java
@@ -39,7 +39,7 @@ public class EntityHitListener extends BaseListener {
             prey = (((Wolf) e.getEntity()).getOwner() == null) ? e.getEntity() : (Entity) ((Wolf) e.getEntity()).getOwner();
         } else prey = e.getEntity();

-        if (e.getDamager() instanceof Arrow) {
+        if (e.getDamager() instanceof Arrow && ((Projectile) e.getDamager()).getShooter() instanceof Entity) {
             hunter = (Entity) ((Projectile) e.getDamager()).getShooter();
         } else if (allowTamedWolves && e.getDamager() instanceof Wolf) {
             hunter = (((Wolf) e.getDamager()).getOwner() == null) ? e.getDamager() : (Entity) ((Wolf) e.getDamager()).getOwner();
```

Tested by opping a player and having them give themselves a dispenser and shoot themselves. Before patching, it reproduced the issue. After installing this patch, shooting themselves no longer triggered a traceback.

**Comment by JeannotM** [comment]
Thanks again for bringing this to my attention, I've added your solution in the latest patch and I hope you have a nice day!
