### ISSUE TITLE
[1.6] data.yml not found

### ISSUE THREAD

**Issue by noiverre** [JeannotM/DynamicDifficulty#7]
Steps:
1. Install DD
2. Start the server

Logs:
```
[01:04:57 INFO]: [DynamicDifficulty] Enabling DynamicDifficulty v1.6
[01:04:57 WARN]: java.lang.IllegalArgumentException: The embedded resource 'data.yml' cannot be found in plugins/DynamicDifficulty v1.6.jar
[01:04:57 WARN]:        at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:193)
[01:04:57 WARN]:        at DynamicDifficulty v1.6.jar//me.skinnyjeans.gmd.databases.File.<init>(File.java:22)
[01:04:57 WARN]:        at DynamicDifficulty v1.6.jar//me.skinnyjeans.gmd.managers.DataManager.<init>(DataManager.java:47)
[01:04:57 WARN]:        at DynamicDifficulty v1.6.jar//me.skinnyjeans.gmd.managers.MainManager.<init>(MainManager.java:24)
[01:04:57 WARN]:        at DynamicDifficulty v1.6.jar//me.skinnyjeans.gmd.Main.onEnable(Main.java:18)
[01:04:57 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[01:04:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[01:04:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
[01:04:57 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561)
[01:04:57 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475)
[01:04:57 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633)
[01:04:57 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
[01:04:57 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[01:04:57 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1121)
[01:04:57 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[01:04:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:04:57 INFO]: [DynamicDifficulty] Can't connect to the database, switching to 'file' mode
[01:04:57 ERROR]: Error occurred while enabling DynamicDifficulty v1.6 (Is it up to date?)
java.lang.IllegalArgumentException: The embedded resource 'data.yml' cannot be found in plugins/DynamicDifficulty v1.6.jar
at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:193) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
at me.skinnyjeans.gmd.databases.File.<init>(File.java:22) ~[DynamicDifficulty v1.6.jar:?]
at me.skinnyjeans.gmd.managers.DataManager.<init>(DataManager.java:51) ~[DynamicDifficulty v1.6.jar:?]
at me.skinnyjeans.gmd.managers.MainManager.<init>(MainManager.java:24) ~[DynamicDifficulty v1.6.jar:?]
at me.skinnyjeans.gmd.Main.onEnable(Main.java:18) ~[DynamicDifficulty v1.6.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.jar:git-Paper-39]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.19.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-39]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-39]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:04:57 INFO]: [DynamicDifficulty] Disabling DynamicDifficulty v1.6
```

Running 1.19 paper build 39 with no PlaceholderAPI installed

**Comment by JeannotM** [comment]
Hey, thanks for sending me this. I've fixed the issue in the latest update you can download on spigot https://www.spigotmc.org/resources/dynamic-difficulty.92025/
